### PR TITLE
Content Type Manager: Update removes Name/Description translations

### PR DESCRIPTION
**Pull request by blankse**
If I translate the name/description fields with an update, the other translations will be removed.

### CODE REVIEW

**Comment by gggeek** [comment]
Interesting find. Do you have a migration that I could use as test ?

**Comment by blankse** [comment]
After this migration the content type should have only a german language:
https://gist.github.com/blankse/e17f5c1990595de9b2d0c83a85b6b2b7

**Comment by blankse** [comment]
Besides the main language will changed of course... So I must make another step to set it back.

Would it not be better, if we can set associative arrays to name and description with language keys? So we can hold the main language to eng-GB and we can set all languages in one step.

**Comment by gggeek** [comment]
Tbh when the migration bundle started it was pretty much monolingual. We added support for different languages progressively, but it is definitely not perfect yet.
I do appreciate any suggestion (and testing) from from fellow devs... but might not have time to dig into this for at least a few days

**Comment by blankse** [comment]
I create a own PR for my improvement thought
https://github.com/kaliop-uk/ezmigrationbundle/pull/126

**Comment by blankse** [comment]
Close in favor of https://github.com/kaliop-uk/ezmigrationbundle/pull/126

**Pull request closed without merging**
